version: '3.8'
services:
  app:
    container_name: myBlog
    build: ./
    ports:
      - "22428:3000"
    depends_on:
      - mysqlblog
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  mysqlblog:
    container_name: myBlog_mysql
    build: ./dockerfiles/mysql
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init-db.sql
volumes:
    mysql-data:
        driver: "local"